/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ErrorLog } from "./ErrorLog";
import { ErrorLogCountArgs } from "./ErrorLogCountArgs";
import { ErrorLogFindManyArgs } from "./ErrorLogFindManyArgs";
import { ErrorLogFindUniqueArgs } from "./ErrorLogFindUniqueArgs";
import { DeleteErrorLogArgs } from "./DeleteErrorLogArgs";
import { ErrorLogService } from "../errorLog.service";
@graphql.Resolver(() => ErrorLog)
export class ErrorLogResolverBase {
  constructor(protected readonly service: ErrorLogService) {}

  async _errorLogsMeta(
    @graphql.Args() args: ErrorLogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ErrorLog])
  async errorLogs(
    @graphql.Args() args: ErrorLogFindManyArgs
  ): Promise<ErrorLog[]> {
    return this.service.errorLogs(args);
  }

  @graphql.Query(() => ErrorLog, { nullable: true })
  async errorLog(
    @graphql.Args() args: ErrorLogFindUniqueArgs
  ): Promise<ErrorLog | null> {
    const result = await this.service.errorLog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ErrorLog)
  async deleteErrorLog(
    @graphql.Args() args: DeleteErrorLogArgs
  ): Promise<ErrorLog | null> {
    try {
      return await this.service.deleteErrorLog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
