/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ErrorLogService } from "../errorLog.service";
import { ErrorLogCreateInput } from "./ErrorLogCreateInput";
import { ErrorLog } from "./ErrorLog";
import { ErrorLogFindManyArgs } from "./ErrorLogFindManyArgs";
import { ErrorLogWhereUniqueInput } from "./ErrorLogWhereUniqueInput";
import { ErrorLogUpdateInput } from "./ErrorLogUpdateInput";

export class ErrorLogControllerBase {
  constructor(protected readonly service: ErrorLogService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ErrorLog })
  async createErrorLog(
    @common.Body() data: ErrorLogCreateInput
  ): Promise<ErrorLog> {
    return await this.service.createErrorLog({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ErrorLog] })
  @ApiNestedQuery(ErrorLogFindManyArgs)
  async errorLogs(@common.Req() request: Request): Promise<ErrorLog[]> {
    const args = plainToClass(ErrorLogFindManyArgs, request.query);
    return this.service.errorLogs({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ErrorLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async errorLog(
    @common.Param() params: ErrorLogWhereUniqueInput
  ): Promise<ErrorLog | null> {
    const result = await this.service.errorLog({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ErrorLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateErrorLog(
    @common.Param() params: ErrorLogWhereUniqueInput,
    @common.Body() data: ErrorLogUpdateInput
  ): Promise<ErrorLog | null> {
    try {
      return await this.service.updateErrorLog({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ErrorLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteErrorLog(
    @common.Param() params: ErrorLogWhereUniqueInput
  ): Promise<ErrorLog | null> {
    try {
      return await this.service.deleteErrorLog({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
