/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProcessedBlogPost } from "./ProcessedBlogPost";
import { ProcessedBlogPostCountArgs } from "./ProcessedBlogPostCountArgs";
import { ProcessedBlogPostFindManyArgs } from "./ProcessedBlogPostFindManyArgs";
import { ProcessedBlogPostFindUniqueArgs } from "./ProcessedBlogPostFindUniqueArgs";
import { DeleteProcessedBlogPostArgs } from "./DeleteProcessedBlogPostArgs";
import { ProcessedBlogPostService } from "../processedBlogPost.service";
@graphql.Resolver(() => ProcessedBlogPost)
export class ProcessedBlogPostResolverBase {
  constructor(protected readonly service: ProcessedBlogPostService) {}

  async _processedBlogPostsMeta(
    @graphql.Args() args: ProcessedBlogPostCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProcessedBlogPost])
  async processedBlogPosts(
    @graphql.Args() args: ProcessedBlogPostFindManyArgs
  ): Promise<ProcessedBlogPost[]> {
    return this.service.processedBlogPosts(args);
  }

  @graphql.Query(() => ProcessedBlogPost, { nullable: true })
  async processedBlogPost(
    @graphql.Args() args: ProcessedBlogPostFindUniqueArgs
  ): Promise<ProcessedBlogPost | null> {
    const result = await this.service.processedBlogPost(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProcessedBlogPost)
  async deleteProcessedBlogPost(
    @graphql.Args() args: DeleteProcessedBlogPostArgs
  ): Promise<ProcessedBlogPost | null> {
    try {
      return await this.service.deleteProcessedBlogPost(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
